### ISSUE TITLE
Array to string conversion error in ScriptHandler::initializeApplication

### ISSUE THREAD

**Issue by fritzmg** [contao/contao#1956]
**Affected version(s)**

Contao 4.10.0-RC1

**Description**

The execution of the ScriptHandler of the manager-bundle in the Managed Edition is currently broken due to the changes introduced in https://github.com/contao/contao/pull/1917.

The code inspector probably wrongly assumes, that the version of `symfony/process` in use for the ScriptHandler is the one from the Contao dependencies. However, that is not the case within the `composer.phar`, as it brings its own `symfony/process` dependency - and it only uses a lower version, where the first constructor argument of `Process` _must_ be a string, not an array.

Thus we currently get the following output during `composer install/update`:

```
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception

  [ErrorException]
  Array to string conversion
```

For reference: the version of `symfony/process` used by the latest stable version of composer (`1.10.9`) is `2.8.52`: https://github.com/composer/composer/blob/83c3250093d5491600a822e176b107a945baf95a/composer.lock#L864

And in version `2.8.52` of `symfony/process` the constructor of `Process` the first parameter needs to be a `string`, not an `array`: https://github.com/symfony/process/blob/c3591a09c78639822b0b290d44edb69bf9f05dc8/Process.php#L127-L137

**Comment by fritzmg** [comment]
Stack Trace:

```
Array to string conversion in phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/process/Process.php in line 263
#0 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/process/Process.php(263): Composer\Util\ErrorHandler::handle(8, 'Array to string...', 'phar://C:/Users...', 263, Array)
#1 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/process/Process.php(196): Symfony\Component\Process\Process->start(Object(Closure))
#2 C:\Users\fritzmg\www\c49dev\vendor\contao\contao\manager-bundle\src\Composer\ScriptHandler.php(91): Symfony\Component\Process\Process->run(Object(Closure))
#3 C:\Users\fritzmg\www\c49dev\vendor\contao\contao\manager-bundle\src\Composer\ScriptHandler.php(31): Contao\ManagerBundle\Composer\ScriptHandler::executeCommand(Array, Object(Composer\Script\Event))
#4 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(305): Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication(Object(Composer\Script\Event))
#5 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(209): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript('Contao\\ManagerB...', 'initializeAppli...', Object(Composer\Script\Event))
#6 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(96): Composer\EventDispatcher\EventDispatcher->doDispatch(Object(Composer\Script\Event))
#7 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/Installer.php(338): Composer\EventDispatcher\EventDispatcher->dispatchScript('post-install-cm...', true)
#8 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#9 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar://C:/Users/fritzmg/scoop/apps/composer/1.10.9/composer.phar/bin/composer(61): Composer\Console\Application->run()
#16 C:\Users\fritzmg\scoop\apps\composer\1.10.9\composer.phar(24): require('phar://C:/Users...')
#17 {main}
```

This seems to be a pretty interesting case. Obviously the `contao/manager-bundle` requests `"symfony/process": "4.4.*"` in its dependencies. However, since the Composer Phar comes with its own `symfony/process` dependency, it seems to take precedence over the one in `vendor/` then? If that's the case, how can you be sure of any dependencies for composer script handlers?
