### ISSUE TITLE
Issue with subprocesses in ResizeImagesCommand

### ISSUE THREAD

**Issue by Toflar** [contao/contao#2176]
**Affected version(s)**

4.9

**Description**

Stacktrace:

```
Symfony\Component\Process\Exception\ProcessSignaledException: The process has been signaled with signal "11".
#11 /vendor/symfony/process/Process.php(428): Symfony\Component\Process\Process::wait
#10 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(355): Contao\CoreBundle\Command\ResizeImagesCommand::finishSubProcess
#9 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(286): Contao\CoreBundle\Command\ResizeImagesCommand::executeConcurrent
#8 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(196): Contao\CoreBundle\Command\ResizeImagesCommand::resizeImages
#7 /vendor/contao/core-bundle/src/Command/ResizeImagesCommand.php(160): Contao\CoreBundle\Command\ResizeImagesCommand::execute
#6 /vendor/symfony/console/Command/Command.php(255): Symfony\Component\Console\Command\Command::run
#5 /vendor/symfony/console/Application.php(1018): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/framework-bundle/Console/Application.php(97): Symfony\Bundle\FrameworkBundle\Console\Application::doRunCommand
#3 /vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application::doRun
#2 /vendor/symfony/framework-bundle/Console/Application.php(83): Symfony\Bundle\FrameworkBundle\Console\Application::doRun
#1 /vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application::run
#0 /vendor/contao/manager-bundle/bin/contao-console(38): null
```

`11` is segfault. I think we should catch those because if one subprocess fails all that happens is that the respective image is not created which is no big deal. However, right now it stops the parent process from continuing to work on all the other images. I think we should try-catch-wrap those.
However, I'm not sure if we should somehow check the number of failures and compare it with the total number of processes executed. If all of them fail, something might be wrong. If one out of 100 fails, it's no big deal...

/cc @ausi

**Comment by ausi** [comment]
Closed in favor of #2182
