### ISSUE TITLE
post-update-cmd fails with error code 255 (4.11)

### ISSUE THREAD

**Issue by ameotoko** [contao/contao#2844]
When upgrading managed edition 4.10 to 4.11, `composer update` fails with `Script @php vendor/bin/contao-setup handling the post-update-cmd event returned with error code 255`:

```console
...
Generating autoload files
> post-autoload-dump: PackageVersions\Installer->dumpVersionsClass
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> post-update-cmd: ContaoCommunityAlliance\Composer\Plugin\Plugin->dumpRunonce
> post-update-cmd: Contao\ManagerPlugin\Composer\ManagerPluginInstaller->dumpPlugins
contao/manager-plugin: Generating plugin class...
 - Added plugin for contao/calendar-bundle
 - Added plugin for contao/comments-bundle
 - Added plugin for contao/core-bundle
 - Added plugin for contao/faq-bundle
 - Added plugin for contao/installation-bundle
 - Added plugin for contao/listing-bundle
 - Added plugin for contao/manager-bundle
 - Added plugin for contao/news-bundle
 - Added plugin for terminal42/contao-fineuploader
 - Added plugin for terminal42/contao-folderpage
 - Added plugin for terminal42/contao-url-rewrite
 - Added plugin for terminal42/dc_multilingual
contao/manager-plugin: ...done generating plugin class
> post-update-cmd: Google\Task\Composer::cleanup
> post-update-cmd: @php vendor/bin/contao-setup
Executing command (CWD): '/Applications/MAMP/bin/php/php7.3.9/bin/php' -d allow_url_fopen='1' -d disable_functions='' -d memory_limit='-1' vendor/bin/contao-setup
Script @php vendor/bin/contao-setup handling the post-update-cmd event returned with error code 255
```

This does not happen on a fresh install (i.e. `composer create-project contao/managed-edition folder 4.11`)

**Comment by fritzmg** [comment]
Can you please check if the file `vendor/bin/contao-setup` actually exists?

**Comment by ameotoko** [comment]
Yes it does:

```console
ll vendor/bin/contao-setup
lrwxr-xr-x  1 andrey  staff    41B Mar  4 20:53 vendor/bin/contao-setup@ -> ../contao/manager-bundle/bin/contao-setup
ll vendor/contao/manager-bundle/bin/contao-setup
-rwxr-xr-x  1 andrey  staff   1.1K Mar  3 18:15 vendor/contao/manager-bundle/bin/contao-setup*
```

**Comment by fritzmg** [comment]
> When upgrading managed edition 4.10 to 4.11

How did you do that update? Via the Contao Manager or manually on the console? What changes did you make?

**Comment by ameotoko** [comment]
I usually adjust my `composer.json` according to the desired branch of `contao/managed-edition`, i.e. https://github.com/contao/managed-edition/blob/4.11/composer.json in this case, and then do `composer update`.

**Comment by fritzmg** [comment]
I see, so you also updated the `script` part of your `composer.json` at the same time, I presume?

@m-vo should that matter though? I thought that the content in `vendor/bin/` is created by Composer before the scripts are run.

**Comment by ameotoko** [comment]
> I see, so you also updated the `script` part of your `composer.json` at the sime time, I presume?

Yes, I did. Here is my current `composer.json`, with which `composer update` is failing:

```json
{
    "name": "contao/managed-edition",
    "type": "project",
    "description": "Contao Open Source CMS",
    "license": "LGPL-3.0-or-later",
    "authors": [
        {
            "name": "Leo Feyer",
            "homepage": "https://github.com/leofeyer"
        }
    ],
    "require": {
        "php": "^7.3",
        "contao/calendar-bundle": "^4.11",
        "contao/conflicts": "@dev",
        "contao/manager-bundle": "4.11.*",
        "terminal42/contao-easy_themes": "^2.2",
        "terminal42/contao-changelanguage": "^3.1",
        "terminal42/contao-ajaxform": "^1.1",
        "terminal42/dc_multilingual": "^4.0",
        "numero2/contao-opengraph3": "^4.1",
        "contao/comments-bundle": "^4.11",
        "terminal42/contao-fineuploader": "^3.0",
        "terminal42/notification_center": "^1.5",
        "ext-json": "*",
        "codefog/contao-cookiebar": "^2.3",
        "eluceo/ical": "^0.16.0",
        "zmyslny/contao-wrapper_tags": "^2.1",
        "terminal42/contao-url-rewrite": "^1.3",
        "terminal42/contao-mailusername": "^1.0",
        "terminal42/contao-mp_forms": "^4.1",
        "terminal42/contao-countryselect": "^1.4",
        "terminal42/contao-conditionalformfields": "^2.3",
        "contao/listing-bundle": "^4.11",
        "contao/news-bundle": "^4.11",
        "terminal42/contao-folderpage": "^2.0",
        "stripe/stripe-php": "^7.67",
        "google/apiclient": "^2.8",
        "guzzlehttp/guzzle": "^6.2.1",
        "mailchimp/marketing": "^3.0",
        "contao/faq-bundle": "^4.11"
    },
    "conflict": {
        "contao-components/installer": "<1.3"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        },
        "classmap": ["src/DataContainer/"]
    },
    "extra": {
        "contao-component-dir": "assets",
        "symfony": {
            "require": "^4.4.*"
        },
        "google/apiclient-services": ["Drive"]
    },
    "scripts": {
        "post-install-cmd": [
            "Google\\Task\\Composer::cleanup",
            "@php vendor/bin/contao-setup"
        ],
        "post-update-cmd": [
            "Google\\Task\\Composer::cleanup",
            "@php vendor/bin/contao-setup"
        ]
    },
    "require-dev": {
        "symfony/phpunit-bridge": "^5.2",
        "contao/test-case": "^4.2"
    }
}
```

**Comment by fritzmg** [comment]
Does the error still occur when you run `composer update` again?

**Comment by ameotoko** [comment]
> Does the error still occur when you run `composer update` again?

Yes, the error persists.

**Comment by ameotoko** [comment]
I also tried:

- removing `Google\\Task\\Composer::cleanup` from `post-update-cmd` array
- running just `composer run post-update-cmd`
- `rm -rf vendor/ && composer update`
- `php vendor/bin/contao-setup` manually

**Comment by fritzmg** [comment]
> * `php vendor/bin/contao-setup` manually

What happens then?

**Comment by ameotoko** [comment]
> What happens then?

Same thing. 😁 Except it fails silently.

**Comment by fritzmg** [comment]
Since `vendor/bin/contao-setup` is a symlink to `../contao/manager-bundle/bin/contao-setup`: is the symlink valid?

**Comment by ameotoko** [comment]
The symlink is valid, as I have shown above; I can also execute it directly, with the same outcome (silent fail)

> Yes it does:
> 
> ```
> ll vendor/bin/contao-setup
> lrwxr-xr-x  1 andrey  staff    41B Mar  4 20:53 vendor/bin/contao-setup@ -> ../contao/manager-bundle/bin/contao-setup
> ll vendor/contao/manager-bundle/bin/contao-setup
> -rwxr-xr-x  1 andrey  staff   1.1K Mar  3 18:15 vendor/contao/manager-bundle/bin/contao-setup*
> ```

**Comment by ameotoko** [comment]
I'm trying to debug, and it seems that Symfony Kernel fails trying to compile the container here: 

https://github.com/symfony/http-kernel/blob/d162d4514e915a9e0c91d9ec7f4232bd25aaf119/Kernel.php#L538-L549

**Comment by m-vo** [comment]
> should that matter though? I thought that the content in vendor/bin/ is created by Composer before the scripts are run.

No, that should totally work - it's the same when running a fresh install on our default managed edition `composer.json`. :slightly_smiling_face: 

-----

I reproduced the issue with your requirements: The error originates from `terminal42/contao-url-rewrite` - and for me removing the package solved it. 

Here is a stack trace:

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /var/www/html/learn/debug/vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php on line 24 and at least 1 expected in /var/www/html/learn/debug/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Stack trace:
#0 /var/www/html/learn/debug/vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php(24): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
#1 /var/www/html/learn/debug/vendor/symfony/config/Definition/Processor.php(50): Terminal42\UrlRewriteBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
#2 /var/www/html/learn/debug/vendor/symfony/dependency-injection/Extension/Extension.php(111): Symfony\Component\Config\Definition\Processor->processConfiguration(Object(Terminal42\UrlRewriteBundle\DependencyInjection\Configuration), Array)
#3 /var/www/html/learn/debug/vendor/symfony/htt in /var/www/html/learn/debug/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
```

But no matter the error - I wonder why this stack trace was not output in your case. Did you try running in verbose mode explicitly? (`composer run post-update-cmd -- -vvv` or `vendor/bin/contao-setup -vvv`)

**Comment by ameotoko** [comment]
@m-vo you beat me to it, I was too slow to type my reply😁

Anyway – I confirm that `terminal42/contao-url-rewrite` is the culprit. The problem is – it tries to instantiate `symfony/config/Definition/Builder/TreeBuilder`, whose constructor signature has been changed in S5. So I guess, my issue can also be solved by locking Symfony at 4.4.* for now. Btw, how do I do it properly? `manager-bundle` requires all the Symfony bundles one by one, should I do the same?

**Comment by fritzmg** [comment]
> Btw, how do I do it properly?

In this case you could either add a conflict for `symfony/config: ^5.0` or add a requirement for `symfony/config: ^4.4` to your `composer.json`.

Make sure to report this error also here: https://github.com/terminal42/contao-url-rewrite/issues

**Comment by ameotoko** [comment]
> But no matter the error - I wonder why this stack trace was not output in your case. Did you try running in verbose mode explicitly? (`composer run post-update-cmd -- -vvv` or `vendor/bin/contao-setup -vvv`)

Yes, I did, the log in my original post is the output with `-vvv`.

But guess what: this incompatibility issue also breaks contao console completely, and _in this case_ I get the full stack trace. I didn't pay attention to it first, because I thought it is a consequence of failed update. 🤦‍♂️

```
ArgumentCountError {#4049
  #message: "Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /Users/andrey/Sites/classic-at-home/vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php on line 24 and at least 1 expected"
  #code: 0
  #file: "./vendor/symfony/config/Definition/Builder/TreeBuilder.php"
  #line: 26
  trace: {
    ./vendor/symfony/config/Definition/Builder/TreeBuilder.php:26 { …}
    ./vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php:24 { …}
    ./vendor/symfony/config/Definition/Processor.php:50 { …}
    ./vendor/symfony/dependency-injection/Extension/Extension.php:111 { …}
    ./vendor/symfony/http-kernel/DependencyInjection/ConfigurableExtension.php:35 { …}
    ./vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76 { …}
    ./vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39 { …}
    ./vendor/symfony/dependency-injection/Compiler/Compiler.php:91 { …}
    ./vendor/symfony/dependency-injection/ContainerBuilder.php:736 { …}
    ./vendor/symfony/http-kernel/Kernel.php:541 { …}
    ./vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php:311 { …}
    ./vendor/symfony/http-kernel/Kernel.php:780 { …}
    ./vendor/symfony/http-kernel/Kernel.php:121 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:168 { …}
    ./vendor/symfony/framework-bundle/Console/Application.php:74 { …}
    ./vendor/symfony/console/Application.php:166 { …}
    ./vendor/contao/manager-bundle/bin/contao-console:37 { …}
  }
}
```

**Comment by m-vo** [comment]
That's a bit unfortunate, though. I got the stack trace right away (even without `-vvv`) and we should IMHO make sure this is always the case. Do we need to set some error reporting levels in the binary? :thinking:

**Comment by m-vo** [comment]
@ameotoko Could you insert these lines into the `contao-setup` file (right at the beginning near the other declarations) and run it again?

```php
error_reporting(-1);
@ini_set('display_startup_errors', '1');
@ini_set('display_errors', '1');
```

**Comment by ameotoko** [comment]
Adding a conflict for `symfony/config: ^5.0` solved the original issue. 

> @ameotoko Could you insert these lines into the `contao-setup` file (right at the beginning near the other declarations) and run it again?

Just a minute... let me try to revert my successful update😁

**Comment by ameotoko** [comment]
Well, that's more like it😁

```
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
85 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
> Google\Task\Composer::cleanup
> @php vendor/bin/contao-setup

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /Users/andrey/Sites/classic-at-home/vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php on line 24 and at least 1 expected in /Users/andrey/Sites/classic-at-home/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26

ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /Users/andrey/Sites/classic-at-home/vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php on line 24 and at least 1 expected in /Users/andrey/Sites/classic-at-home/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26

Call Stack:
    0.0138     407832   1. {main}() /Users/andrey/Sites/classic-at-home/vendor/contao/manager-bundle/bin/contao-setup:0
    0.3141    8323272   2. Contao\ManagerBundle\Console\ContaoApplication->run(???, ???) /Users/andrey/Sites/classic-at-home/vendor/contao/manager-bundle/bin/contao-setup:44
    0.3389    8614480   3. Contao\ManagerBundle\Console\ContaoApplication->doRun(???, ???) /Users/andrey/Sites/classic-at-home/vendor/symfony/console/Application.php:166
    0.3389    8614480   4. Contao\ManagerBundle\Console\ContaoApplication->registerCommands() /Users/andrey/Sites/classic-at-home/vendor/symfony/framework-bundle/Console/Application.php:74
    0.3389    8614480   5. Contao\ManagerBundle\HttpKernel\ContaoKernel->boot() /Users/andrey/Sites/classic-at-home/vendor/symfony/framework-bundle/Console/Application.php:168
    0.3389    8614480   6. Contao\ManagerBundle\HttpKernel\ContaoKernel->preBoot() /Users/andrey/Sites/classic-at-home/vendor/symfony/http-kernel/Kernel.php:121
    0.4999    9972392   7. Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() /Users/andrey/Sites/classic-at-home/vendor/symfony/http-kernel/Kernel.php:780
    0.4999    9972392   8. Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() /Users/andrey/Sites/classic-at-home/vendor/contao/manager-bundle/src/HttpKernel/ContaoKernel.php:311
    1.2493   20713176   9. Contao\ManagerPlugin\Config\ContainerBuilder->compile(???) /Users/andrey/Sites/classic-at-home/vendor/symfony/http-kernel/Kernel.php:541
    1.2776   20725624  10. Symfony\Component\DependencyInjection\Compiler\Compiler->compile(???) /Users/andrey/Sites/classic-at-home/vendor/symfony/dependency-injection/ContainerBuilder.php:736
    1.2777   20737968  11. Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(???) /Users/andrey/Sites/classic-at-home/vendor/symfony/dependency-injection/Compiler/Compiler.php:91
    1.3239   21356720  12. Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(???) /Users/andrey/Sites/classic-at-home/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php:39
    3.5677   32466088  13. Terminal42\UrlRewriteBundle\DependencyInjection\Terminal42UrlRewriteExtension->load(???, ???) /Users/andrey/Sites/classic-at-home/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php:76
    3.5680   32466128  14. Terminal42\UrlRewriteBundle\DependencyInjection\Terminal42UrlRewriteExtension->processConfiguration(???, ???) /Users/andrey/Sites/classic-at-home/vendor/symfony/http-kernel/DependencyInjection/ConfigurableExtension.php:35
    3.5681   32466168  15. Symfony\Component\Config\Definition\Processor->processConfiguration(???, ???) /Users/andrey/Sites/classic-at-home/vendor/symfony/dependency-injection/Extension/Extension.php:111
    3.5681   32466168  16. Terminal42\UrlRewriteBundle\DependencyInjection\Configuration->getConfigTreeBuilder() /Users/andrey/Sites/classic-at-home/vendor/symfony/config/Definition/Processor.php:50
    3.5681   32466248  17. Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct(???, ???, ???) /Users/andrey/Sites/classic-at-home/vendor/terminal42/contao-url-rewrite/src/DependencyInjection/Configuration.php:24

Script @php vendor/bin/contao-setup handling the post-update-cmd event returned with error code 255
```

**Comment by ameotoko** [comment]
Should I close then? The original issue seem to be unrelated to Contao and has been solved.

**Comment by m-vo** [comment]
> Well, that's more like itgrin

Yes, I agree! I'll provide a PR to improve the situation.

**Comment by ameotoko** [comment]
Thank you @fritzmg and @m-vo!
