### ISSUE TITLE
You have requested a non-existent service "contao.monolog.logger.error

### ISSUE THREAD

**Issue by Seefahrer** [contao/contao#4058]
### Affected version(s)

4.13.0-RC1

### Description

In a local MAMP 6.6.1 clone of my private site (https./www.luetten-dieks.eu) I get fllwg errorand the frontend is no longer reachable:

> `request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "You have requested a non-existent service "contao.monolog.logger.error"." at /Users/georg/Websites/cmsc4ME/vendor/symfony/dependency-injection/Container.php line 271 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\ServiceNotFoundException(code: 0): You have requested a non-existent service \"contao.monolog.logger.error\“`

**Comment by m-vo** [comment]
Please enable the debug mode and post the full stack trace.

**Comment by Seefahrer** [comment]
Not sure that the stack trace really helps ... starts with an EasyTheme related warning. The error disappears after downgrading to 4.12.5 and reappears after the next upgrade to 4.13.0-RC1.

> ErrorException:
Warning: Undefined global variable $TL_EASY_THEMES_MODULES

  ```
at vendor/terminal42/contao-easy_themes/config/config.php:65
  at include('/Users/georg/Websites/cmsc4ME/vendor/terminal42/contao-easy_themes/config/config.php')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php:200)
  at Contao\Config->initialize()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Config.php:165)
  at Contao\Config::getInstance()
     (vendor/contao/core-bundle/src/Framework/Adapter.php:46)
  at Contao\CoreBundle\Framework\Adapter->__call('getInstance', array())
     (vendor/contao/core-bundle/src/Framework/ContaoFramework.php:272)
  at Contao\CoreBundle\Framework\ContaoFramework->initializeFramework()
     (vendor/contao/core-bundle/src/Framework/ContaoFramework.php:116)
  at Contao\CoreBundle\Framework\ContaoFramework->initialize(true)
     (vendor/contao/core-bundle/src/Routing/RouteProvider.php:46)
  at Contao\CoreBundle\Routing\RouteProvider->getRouteCollectionForRequest(object(Request))
     (vendor/symfony-cmf/routing/src/NestedMatcher/NestedMatcher.php:140)
  at Symfony\Cmf\Component\Routing\NestedMatcher\NestedMatcher->matchRequest(object(Request))
     (vendor/symfony-cmf/routing/src/DynamicRouter.php:272)
  at Symfony\Cmf\Component\Routing\DynamicRouter->matchRequest(object(Request))
     (vendor/symfony-cmf/routing/src/ChainRouter.php:188)
  at Symfony\Cmf\Component\Routing\ChainRouter->doMatch('/', object(Request))
     (vendor/symfony-cmf/routing/src/ChainRouter.php:158)
  at Symfony\Cmf\Component\Routing\ChainRouter->matchRequest(object(Request))
     (vendor/symfony/http-kernel/EventListener/RouterListener.php:111)
  at Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(object(RequestEvent), 'kernel.request', object(TraceableEventDispatcher))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners(array(object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener), object(WrappedListener)), 'kernel.request', object(RequestEvent))
     (vendor/symfony/event-dispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:154)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(object(RequestEvent), 'kernel.request')
     (vendor/symfony/http-kernel/HttpKernel.php:128)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:44)   

```

**Comment by m-vo** [comment]
Your second error appears to be unrelated to the one in your initial posting. 

> Not sure that the stack trace really helps

Well, yes, like you found out yourself it originates in `vendor/terminal42/contao-easy_themes/config/config.php` on L65. :slightly_smiling_face:  So at least this error should rather be posted over at the [terminal42 repository](https://github.com/terminal42/contao-easy_themes/issues). 

Edit: In fact there is already an issue for this same problem: https://github.com/terminal42/contao-easy_themes/issues/52

**Comment by Seefahrer** [comment]
The main issue remains the one given in my initial posting. Obviously there is no stack trace for this error.
The Easytheme error does not result in the site becoming unreachable. The initially reported error does.

As mentioned above the monolog error disappears after a 4.12.5 downgrade and reappears after upgrading again to 4.13.

**Comment by m-vo** [comment]
> The main issue remains the one given in my initial posting. 

But it's hard to find the root cause without a stack trace or any more information. If the easy themes error shadows the original error, please make sure to resolve this first (e.g. maybe by temporarily uninstalling easy themes).

**Comment by Seefahrer** [comment]
Even despite removal of nearly all installed extensions, the error was at least „non stack traceable“ ...
But nevertheless I could find out that the initially reported error was caused by some erroneous „pct revolution slider“ script/template/whatever ... So finally I could fix it myself.

As it is not Contao core related, the issue might be closed ...

**Comment by aschempp** [comment]
I just had this same error in a content element fragment that included an image, because the image was missing. As soon as I added the image, the error was gone (obviously).

```
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "contao.monolog.logger.error".
#32 /vendor/symfony/dependency-injection/Container.php(271): Symfony\Component\DependencyInjection\Container::make
#31 /vendor/symfony/dependency-injection/Container.php(219): Symfony\Component\DependencyInjection\Container::get
#30 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php(1749): Contao\Controller::addImageToTemplate
#29 /src/Controller/ContentElement/LinkboxController.php(50): App\Controller\ContentElement\LinkboxController::getResponse
#28 /vendor/contao/core-bundle/src/Controller/ContentElement/AbstractContentElementController.php(34): Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController::__invoke
#27 /vendor/symfony/http-kernel/HttpKernel.php(152): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#26 /vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel::handle
#25 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(86): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#24 /vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php(80): Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer::render
#23 /vendor/symfony/http-kernel/Fragment/FragmentHandler.php(85): Symfony\Component\HttpKernel\Fragment\FragmentHandler::render
#22 /vendor/contao/core-bundle/src/Fragment/FragmentHandler.php(65): Contao\CoreBundle\Fragment\FragmentHandler::render
#21 /vendor/contao/core-bundle/src/Resources/contao/elements/ContentProxy.php(61): Contao\ContentProxy::generate
#20 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php(598): Contao\Controller::getContentElement
#19 /vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php(202): Contao\ModuleArticle::compile
#18 /vendor/contao/core-bundle/src/Resources/contao/modules/Module.php(216): Contao\Module::generate
#17 /vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php(72): Contao\ModuleArticle::generate
#16 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php(526): Contao\Controller::getArticle
#15 /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php(368): Contao\Controller::getFrontendModule
#14 /vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php(193): Contao\PageRegular::prepare
#13 /vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php(63): Contao\PageRegular::getResponse
#12 /vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php(316): Contao\FrontendIndex::renderPage
#11 /vendor/symfony/http-kernel/HttpKernel.php(152): Symfony\Component\HttpKernel\HttpKernel::handleRaw
#10 /vendor/symfony/http-kernel/HttpKernel.php(74): Symfony\Component\HttpKernel\HttpKernel::handle
#9 /vendor/symfony/http-kernel/Kernel.php(202): Symfony\Component\HttpKernel\Kernel::handle
#8 /vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(86): Symfony\Component\HttpKernel\HttpCache\SubRequestHandler::handle
#7 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(479): Symfony\Component\HttpKernel\HttpCache\HttpCache::forward
#6 /vendor/symfony/framework-bundle/HttpCache/HttpCache.php(73): Symfony\Bundle\FrameworkBundle\HttpCache\HttpCache::forward
#5 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(452): Symfony\Component\HttpKernel\HttpCache\HttpCache::fetch
#4 /vendor/contao/manager-bundle/src/HttpKernel/ContaoCache.php(65): Contao\ManagerBundle\HttpKernel\ContaoCache::fetch
#3 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(346): Symfony\Component\HttpKernel\HttpCache\HttpCache::lookup
#2 /vendor/symfony/http-kernel/HttpCache/HttpCache.php(224): Symfony\Component\HttpKernel\HttpCache\HttpCache::handle
#1 /vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): Contao\ManagerBundle\HttpKernel\ContaoCache::handle
#0 /web/preview.php(46): null
```

**Comment by SeverinGloeckle** [comment]
The service name `contao.monolog.logger.error` is wrong – it has to be `monolog.logger.contao.error`. The same typo exists in `Image.php(892)`.

I will provide a fix.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/4095
