### ISSUE TITLE
contao:backup:restore - There is no active transaction

### ISSUE THREAD

**Issue by contaoacademy** [contao/contao#4129]
### Affected version(s)

4.13-RC3

### Description

When I try to restore a backup with the new `contao:backup:restore` command, I get the following error message:

```
CRITICAL  [console] Error thrown while running command "contao:backup:restore 'backup__20220214130343.sql.gz'". Message: "There is no active transaction" ["exception" => PDOException { …},"command" => "contao:backup:restore 'backup__20220214130343.sql.gz'","message" => "There is no active transaction"]

In Connection.php line 118:

  There is no active transaction


contao:backup:restore [-i|--ignore-tables [IGNORE-TABLES]] [--format FORMAT] [--force] [--] [<name>]
```

- Environment: MAMP Pro 6.6.1
- PHP 8.0.8
- mysql  Ver 14.14 Distrib 5.7.34, for osx10.12 (x86_64)

**Comment by fritzmg** [comment]
Please use `-vvv` and post the stack trace. I cannot reproduce locally.

**Comment by contaoacademy** [comment]
```
CRITICAL  [console] Error thrown while running command "contao:backup:restore 'backup__20220214130343.sql.gz' -vvv". Message: "There is no active transaction"
[
  "exception" => PDOException {
    #message: "There is no active transaction"
    #code: 0
    #file: "./vendor/doctrine/dbal/src/Driver/PDO/Connection.php"
    #line: 118
    +errorInfo: null
    trace: {
      ./vendor/doctrine/dbal/src/Driver/PDO/Connection.php:118 { …}
      ./vendor/doctrine/dbal/src/Connection.php:1349 { …}
      ./vendor/doctrine/dbal/src/Connection.php:1394 { …}
      ./vendor/doctrine/dbal/src/Connection.php:515 { …}
      ./vendor/contao/core-bundle/src/Doctrine/Backup/BackupManager.php:167 { …}
      ./vendor/contao/core-bundle/src/Doctrine/Backup/BackupManager.php:139 { …}
      ./vendor/contao/core-bundle/src/Command/Backup/BackupRestoreCommand.php:50 { …}
      ./vendor/symfony/console/Command/Command.php:298 { …}
      ./vendor/symfony/console/Application.php:1033 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:96 { …}
      ./vendor/symfony/console/Application.php:299 { …}
      ./vendor/symfony/framework-bundle/Console/Application.php:82 { …}
      ./vendor/symfony/console/Application.php:171 { …}
      ./vendor/contao/manager-bundle/bin/contao-console:37 { …}
      ./vendor/bin/contao-console:117 { …}
    }
  },
  "command" => "contao:backup:restore 'backup__20220214130343.sql.gz' -vvv",
  "message" => "There is no active transaction"
]
14:06:47 DEBUG     [console] Command "contao:backup:restore 'backup__20220214130343.sql.gz' -vvv" exited with code "1"
[
  "command" => "contao:backup:restore 'backup__20220214130343.sql.gz' -vvv",
  "code" => 1
]

In Connection.php line 118:

  [PDOException]
  There is no active transaction


Exception trace:
  at /Users/christian/web/cto413/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:118
 PDO->commit() at /Users/christian/web/cto413/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:118
 Doctrine\DBAL\Driver\PDO\Connection->commit() at /Users/christian/web/cto413/vendor/doctrine/dbal/src/Connection.php:1349
 Doctrine\DBAL\Connection->commit() at /Users/christian/web/cto413/vendor/doctrine/dbal/src/Connection.php:1394
 Doctrine\DBAL\Connection->commitAll() at /Users/christian/web/cto413/vendor/doctrine/dbal/src/Connection.php:515
 Doctrine\DBAL\Connection->setAutoCommit() at /Users/christian/web/cto413/vendor/contao/core-bundle/src/Doctrine/Backup/BackupManager.php:167
 Contao\CoreBundle\Doctrine\Backup\BackupManager->executeTransactional() at /Users/christian/web/cto413/vendor/contao/core-bundle/src/Doctrine/Backup/BackupManager.php:139
 Contao\CoreBundle\Doctrine\Backup\BackupManager->restore() at /Users/christian/web/cto413/vendor/contao/core-bundle/src/Command/Backup/BackupRestoreCommand.php:50
 Contao\CoreBundle\Command\Backup\BackupRestoreCommand->execute() at /Users/christian/web/cto413/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at /Users/christian/web/cto413/vendor/symfony/console/Application.php:1033
 Symfony\Component\Console\Application->doRunCommand() at /Users/christian/web/cto413/vendor/symfony/framework-bundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /Users/christian/web/cto413/vendor/symfony/console/Application.php:299
 Symfony\Component\Console\Application->doRun() at /Users/christian/web/cto413/vendor/symfony/framework-bundle/Console/Application.php:82
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/christian/web/cto413/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /Users/christian/web/cto413/vendor/contao/manager-bundle/bin/contao-console:37
 include() at /Users/christian/web/cto413/vendor/bin/contao-console:117

contao:backup:restore [-i|--ignore-tables [IGNORE-TABLES]] [--format FORMAT] [--force] [--] [<name>]
```

**Comment by contaoacademy** [comment]
The problem must be related to my local machine. I just tested it on a remote server, there is no error message.

**Comment by ausi** [comment]
This seems to be a problem in doctrine/dbal `Connection::setAutoCommit(true)` https://github.com/doctrine/dbal/blob/35eae239ef515d55ebb24e9d4715cad09a4f58ed/src/Connection.php#L499-L516 @contaoacademy which version of `doctrine/dbal` is installed in your project?

**Comment by netzarbeiter** [comment]
```bash
name     : doctrine/dbal
versions : * 3.3.2
```

**Comment by contaoacademy** [comment]
```
doctrine/annotations                               1.13.2           Docblock Annotations Parser
doctrine/cache                                     2.1.1            PHP Doctrine Cache library is a popular cache implementation that...
doctrine/collections                               1.6.8            PHP Doctrine Collections library that adds additional functionali...
doctrine/common                                    3.2.2            PHP Doctrine Common project is a library that provides additional...
doctrine/dbal                                      3.3.2            Powerful PHP database abstraction layer (DBAL) with many features...
doctrine/deprecations                              v0.5.3           A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR-3...
doctrine/doctrine-bundle                           2.5.6            Symfony DoctrineBundle
doctrine/event-manager                             1.1.1            The Doctrine Event Manager is a simple PHP event system that was ...
doctrine/inflector                                 2.0.4            PHP Doctrine Inflector is a small library that can perform string...
doctrine/instantiator                              1.4.0            A small, lightweight utility to instantiate objects in PHP withou...
doctrine/lexer                                     1.2.2            PHP Doctrine Lexer parser library that can be used in Top-Down, R...
doctrine/orm                                       2.11.1           Object-Relational-Mapper for PHP
doctrine/persistence                               2.3.0            The Doctrine Persistence project is a set of shared interfaces an...
doctrine/sql-formatter                             1.1.2            a PHP SQL highlighting library
symfony/doctrine-bridge                            v5.4.3           Provides integration for Doctrine with various Symfony components
```

**Comment by ausi** [comment]
We were able to reproduce the issue with this small script:

```php
<?php
$conn = \Doctrine\DBAL\DriverManager::getConnection(
	["url" => "mysql://…:…@localhost/…"]
);
$conn->setAutoCommit(false);
$conn->transactional(function() use ($conn) {
	$conn->query("CREATE TABLE test1234 (id INT AUTO_INCREMENT PRIMARY KEY)");
});
$conn->setAutoCommit(true);
```

Result:

```
Fatal error: Uncaught PDOException: There is no active transaction in /Users/christian/web/cto413/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:118
Stack trace:
#0 /Users/christian/web/cto413/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(118): PDO->commit()
#1 /Users/christian/web/cto413/vendor/doctrine/dbal/src/Connection.php(1349): Doctrine\DBAL\Driver\PDO\Connection->commit()
#2 /Users/christian/web/cto413/vendor/doctrine/dbal/src/Connection.php(1394): Doctrine\DBAL\Connection->commit()
#3 /Users/christian/web/cto413/vendor/doctrine/dbal/src/Connection.php(515): Doctrine\DBAL\Connection->commitAll()
#4 Command line code(1): Doctrine\DBAL\Connection->setAutoCommit(true)
#5 {main}
  thrown in /Users/christian/web/cto413/vendor/doctrine/dbal/src/Driver/PDO/Connection.php on line 118
```

It could have something to do with MySQL not supporting transactions for DDL statements.

**Comment by contaoacademy** [comment]
Hab noch was rausgefunden
Mit PHP 7.4 geht es. Sobald ich wieder auf PHP 8 gehe, kommt das Problem.

Habe noch das dazu gefunden:
https://github.com/doctrine/migrations/blob/3.2.x/docs/en/explanation/implicit-commits.rst

**Comment by ausi** [comment]
Similar issue https://github.com/yiisoft/yii2/issues/18406

> As of PHP 8, `PDO::commit()` and `rollBack()` will throw a `There is no active transaction` PDOException if the transaction had been autocommitted, as MySQL will do whenever a schema change is made. Previously they would fail silently.
