### ISSUE TITLE
InvalidArgumentException: Routing requirement for "_locale" cannot be empty.

### ISSUE THREAD

**Issue by Toflar** [contao/contao#418]
**Affected version(s)**

4.7.*

**Description**  

Apparently the `_locale` parameter is a requirement but we do not seem to add it under all circumstances.

**How to reproduce**  

Hard to tell really. I can provide the following stacktrace for now:

```
InvalidArgumentException: Routing requirement for "_locale" cannot be empty.
#26 vendor/symfony/routing/Route.php(566): sanitizeRequirement
#25 vendor/symfony/routing/Route.php(456): addRequirements
#24 vendor/symfony/routing/Route.php(57): __construct
#23 vendor/contao/core-bundle/src/Routing/RouteProvider.php(310): addRoutesForRootPage
#22 vendor/contao/core-bundle/src/Routing/RouteProvider.php(236): addRoutesForRootPages
#21 vendor/contao/core-bundle/src/Routing/RouteProvider.php(76): getRouteCollectionForRequest
#20 vendor/contao/core-bundle/src/Routing/LegacyRouteProvider.php(43): getRouteCollectionForRequest
#19 vendor/symfony-cmf/routing/src/NestedMatcher/NestedMatcher.php(141): matchRequest
#18 vendor/contao/core-bundle/src/Routing/Matcher/LegacyMatcher.php(69): matchRequest
#17 vendor/symfony-cmf/routing/src/DynamicRouter.php(271): matchRequest
#16 vendor/symfony-cmf/routing/src/ChainRouter.php(188): doMatch
#15 vendor/symfony-cmf/routing/src/ChainRouter.php(158): matchRequest
#14 vendor/symfony/http-kernel/EventListener/RouterListener.php(115): onKernelRequest
#13 vendor/symfony/event-dispatcher/EventDispatcher.php(212): doDispatch
#12 vendor/symfony/event-dispatcher/EventDispatcher.php(44): dispatch
#11 vendor/symfony/http-kernel/HttpKernel.php(126): handleRaw
#10 vendor/symfony/http-kernel/HttpKernel.php(67): handle
#9 vendor/symfony/http-kernel/Kernel.php(198): handle
#8 vendor/symfony/http-kernel/HttpCache/SubRequestHandler.php(85): handle
#7 vendor/symfony/http-kernel/HttpCache/HttpCache.php(448): forward
#6 vendor/symfony/framework-bundle/HttpCache/HttpCache.php(57): forward
#5 vendor/symfony/http-kernel/HttpCache/HttpCache.php(420): fetch
#4 vendor/contao/manager-bundle/src/HttpKernel/ContaoCache.php(46): fetch
#3 vendor/symfony/http-kernel/HttpCache/HttpCache.php(317): lookup
#2 vendor/symfony/http-kernel/HttpCache/HttpCache.php(192): handle
#1 vendor/friendsofsymfony/http-cache/src/SymfonyCache/EventDispatchingHttpCache.php(98): handle
#0 web/app.php(58): null
```

For me, it happended when calliing `https://domain.de/de/` so it must be some root page related thing here.

**Comment by leofeyer** [comment]
Does the issue still occur in Contao 4.7.5?

**Comment by Toflar** [comment]
No reports in Sentry anymore. So I guess this is fixed. I'll reopen if it happens again.
