### ISSUE TITLE
Rebuilding the cache triggers messenger exception

### ISSUE THREAD

**Issue by leofeyer** [contao/contao#5947]
### Affected version(s)

5.1.2

### Description

Rebuilding the cache via `bin/console cache:clear` triggers a messenger exception on my system:

```
Symfony\Component\Messenger\Exception\InvalidArgumentException: You cannot receive messages from the Messenger SyncTransport.
#10 /vendor/symfony/messenger/Transport/Sync/SyncTransport.php(37): Symfony\Component\Messenger\Transport\Sync\SyncTransport::get
#9 /vendor/contao/core-bundle/src/Messenger/Transport/AutoFallbackTransport.php(32): Contao\CoreBundle\Messenger\Transport\AutoFallbackTransport::get
#8 /vendor/symfony/messenger/Worker.php(103): Symfony\Component\Messenger\Worker::run
#7 /vendor/symfony/messenger/Command/ConsumeMessagesCommand.php(229): Symfony\Component\Messenger\Command\ConsumeMessagesCommand::execute
#6 /vendor/symfony/console/Command/Command.php(312): Symfony\Component\Console\Command\Command::run
#5 /vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Application::doRunCommand
#4 /vendor/symfony/framework-bundle/Console/Application.php(88): Symfony\Bundle\FrameworkBundle\Console\Application::doRunCommand
#3 /vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application::doRun
#2 /vendor/symfony/framework-bundle/Console/Application.php(77): Symfony\Bundle\FrameworkBundle\Console\Application::doRun
#1 /vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application::run
#0 /bin/console(28): null
```

@Toflar Any idea what could be causing this?

**Comment by Toflar** [comment]
What's the full stack trace?

**Comment by leofeyer** [comment]
This is the full stack trace according to Sentry.

**Comment by Toflar** [comment]
You said `cache:clear` but the stack trace says `ConsumeMessagesCommand`.

**Comment by leofeyer** [comment]
Yes, the `clear:cache` command completes without errors. A few seconds later, Sentry alerts me about the above exception. Every time I repeat the process.

So I guess clearing the cache removes something the messenger relies on? Maybe clearing the cache should stop the messenger queue first?

**Comment by fritzmg** [comment]
Does it also happen with `cache:clear --no-warmup`?

**Comment by leofeyer** [comment]
The problem hasn‘t occurred again, so I‘m closing the ticket for now.
